name: Data Pipeline 2

on:
  workflow_dispatch: # Allows manual triggering from GitHub UI
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Grants write access to the repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: integration-branch  # Specify the integration branch

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6' # Use the version compatible with your code

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r continente_price_tracker/requirements.txt

      - name: Create .env file
        run: |
          echo "SUPABASE_ACCESS_KEY_ID=${{ secrets.SUPABASE_ACCESS_KEY_ID }}" >> continente_price_tracker/.env
          echo "SUPABASE_SECRET_ACCESS_KEY=${{ secrets.SUPABASE_SECRET_ACCESS_KEY }}" >> continente_price_tracker/.env
          echo "SUPABASE_ENDPOINT=${{ secrets.SUPABASE_ENDPOINT }}" >> continente_price_tracker/.env
          echo "SUPABASE_REGION=${{ secrets.SUPABASE_REGION }}" >> continente_price_tracker/.env
          echo "SUPABASE_BUCKET_NAME=${{ secrets.SUPABASE_BUCKET_NAME }}" >> continente_price_tracker/.env

      - name: Run data pipeline
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: |
          python continente_price_tracker/src/main.py

      - name: Commit and push CSV files
        if: success()
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout integration-branch
          git add .
          timestamp=$(date +'%Y-%m-%d %H:%M:%S')
          git commit -m "Update CSV files - $timestamp" || echo "No changes to commit"
          git push origin integration-branch
